apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-2
  labels:
    app: spring-boot-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app-2
  template:
    metadata:
      labels:
        app: spring-boot-app-2
    spec:
      containers:
      - name: spring-boot-app-2
        image: your-dockerhub-username/springboot-maven-2:0
        ports:
        - containerPort: 8080